[workspace]
resolver = "2"
members = ["kotoshu"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Ribose Inc. <open.source@ribose.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/kotoshu/kotoshu-rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.release.package."*"]
opt-level = "s"
