//! Grammar conformance vectors: generated by the Ruby engine, replayed
//! here. Both engines must produce identical rule ids, offsets, and
//! suggestions for the same inputs.

use kotoshu::grammar::checker::Checker;
use kotoshu::grammar::pattern_rule::{MatcherKind, PatternRule, RuleDef};

const VECTORS: &str = include_str!("../kotoshu/src/grammar/testdata/grammar_vectors.json");

const RULE_FILES: &[(&str, &str)] = &[
    ("agreement", include_str!("../kotoshu/src/grammar/rules/en/agreement.yml")),
    ("agreement2", include_str!("../kotoshu/src/grammar/rules/en/agreement2.yml")),
    ("articles", include_str!("../kotoshu/src/grammar/rules/en/articles.yml")),
    ("confusions", include_str!("../kotoshu/src/grammar/rules/en/confusions.yml")),
    ("mechanics", include_str!("../kotoshu/src/grammar/rules/en/mechanics.yml")),
    ("prepositions", include_str!("../kotoshu/src/grammar/rules/en/prepositions.yml")),
    ("punctuation", include_str!("../kotoshu/src/grammar/rules/en/punctuation.yml")),
    ("redundancy", include_str!("../kotoshu/src/grammar/rules/en/redundancy.yml")),
    ("style", include_str!("../kotoshu/src/grammar/rules/en/style.yml")),
    ("word_confusion", include_str!("../kotoshu/src/grammar/rules/en/word_confusion.yml")),
];

fn bundled_checker() -> Checker {
    let mut rules = Vec::new();
    for (name, yaml) in RULE_FILES {
        let file: Vec<RuleDef> =
            serde_yaml::from_str(yaml).unwrap_or_else(|e| panic!("parse {name}: {e}"));
        for def in &file {
            rules.push(PatternRule::from_def(def));
        }
    }
    Checker::new(rules)
}

#[test]
fn vectors_replay_identically() {
    let vectors: serde_json::Value = serde_json::from_str(VECTORS).unwrap();
    let checker = bundled_checker();
    let mut mismatches = 0;
    for case in vectors.as_array().unwrap() {
        let input = case["input"].as_str().unwrap();
        let expected: Vec<(String, usize, usize, Vec<String>)> = case["errors"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| {
                (
                    e["rule_id"].as_str().unwrap().to_string(),
                    e["start_offset"].as_u64().unwrap() as usize,
                    e["end_offset"].as_u64().unwrap() as usize,
                    e["suggestions"]
                        .as_array()
                        .map(|a| {
                            a.iter()
                                .map(|s| s.as_str().unwrap().to_string())
                                .collect()
                        })
                        .unwrap_or_default(),
                )
            })
            .collect();
        let actual: Vec<(String, usize, usize, Vec<String>)> = checker
            .check(input)
            .iter()
            .map(|e| {
                (
                    e.rule_id.clone(),
                    e.start_offset,
                    e.end_offset,
                    e.suggestions.clone(),
                )
            })
            .collect();
        for exp in &expected {
            if !actual.contains(exp) {
                mismatches += 1;
                eprintln!("MISSING {input:?}: {exp:?} (rust had {actual:?})");
            }
        }
        for act in &actual {
            if !expected.contains(act) {
                mismatches += 1;
                eprintln!("EXTRA {input:?}: {act:?}");
            }
        }
    }
    assert_eq!(mismatches, 0, "conformance mismatches");
}

#[test]
fn all_rule_files_parse() {
    for (name, yaml) in RULE_FILES {
        let file: Result<Vec<RuleDef>, _> = serde_yaml::from_str(yaml);
        assert!(file.is_ok(), "{name} failed to parse: {:?}", file.err());
    }
}

#[test]
fn word_list_matcher_kind_detected() {
    let yaml = RULE_FILES
        .iter()
        .find(|(n, _)| *n == "redundancy")
        .map(|(_, y)| *y)
        .unwrap();
    let file: Vec<RuleDef> = serde_yaml::from_str(yaml).unwrap();
    let rule = file
        .iter()
        .find(|r| r.id == "EN_REDUNDANT_FREE_GIFT")
        .unwrap();
    let built = PatternRule::from_def(rule);
    assert!(matches!(built.matcher, MatcherKind::WordList));
}
