//! Resource handling behind the `resources` feature: parse the models
//! registry (`kotoshu.resources/v1`), resolve `(language, tier)` →
//! resource URLs + sha256, verify downloads, and cache them locally —
//! making the standalone Rust engine self-sufficient for models.
//!
//! Registry shape (spec `kotoshu.resources/v1`, generated by
//! `scripts/build_registry.py` in the models repo; the JSON Schema
//! lives at `schemas/registry.schema.json` there):
//!
//! ```json
//! { "spec": "kotoshu.resources/v1", "registry_version": 1,
//!   "release_tag": "v1.0.1",
//!   "resources": {
//!     "kotoshu://models/en/mini": {
//!       "type": "model", "language": "en",
//!       "tier": { "name": "mini", "dims": 300, "vocab_size": 10000,
//!                 "quantization": "int8-per-row" },
//!       "version": "1.0.1",
//!       "urls": { "primary": "https://github.com/…/fasttext.en.mini.onnx",
//!                 "mirror": "https://github.com/…/raw/main/models/en/fasttext.en.mini.onnx" },
//!       "vocab_url": "https://github.com/…/fasttext.en.mini.vocab.json",
//!       "sha256": "d81f…5e2f", "size_bytes": 3040752, … } } }
//! ```
//!
//! Downloading shells out to the system `curl` — the feature's
//! dependency budget is serde/serde_json/sha2 only, std has no TLS, and
//! vendoring an HTTP stack is an owner decision. Hosts that cannot
//! shell out pre-populate the cache (see [`ResourceCache::model_path`])
//! or call [`ResourceCache::ensure_model_with`] with their own fetch.

use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};

/// The resource spec string; a registry with any other spec is refused.
pub const SPEC: &str = "kotoshu.resources/v1";

/// A parsed registry.
#[derive(Debug, Clone, Deserialize)]
pub struct Registry {
    /// Must be [`SPEC`].
    pub spec: String,
    /// Bumped on incompatible registry content changes.
    pub registry_version: u32,
    /// The release the URLs point at (`v1.0.1`), or null for dev builds.
    pub release_tag: Option<String>,
    /// Resources keyed by id (`kotoshu://models/{lang}/{tier}`).
    pub resources: HashMap<String, Resource>,
}

/// One downloadable model resource.
#[derive(Debug, Clone, Deserialize)]
pub struct Resource {
    /// Always `"model"` in v1.
    pub r#type: String,
    /// ISO 639-1 language code.
    pub language: String,
    /// Tier metadata.
    pub tier: Tier,
    /// Artifact version (`1.0.1`).
    pub version: String,
    /// Download URLs.
    pub urls: Urls,
    /// The vocab.json sibling URL (the model resolves words through it).
    pub vocab_url: Option<String>,
    /// sha256 of the `.onnx` bytes (registry v1 carries no separate
    /// vocab checksum — the per-tier `vocab_sha256` is not exposed at
    /// this spec level).
    pub sha256: String,
    /// Exact `.onnx` size in bytes.
    pub size_bytes: u64,
    /// Lowest engine version that can read the artifact.
    pub min_engine_version: String,
}

/// Tier metadata of a resource.
#[derive(Debug, Clone, Deserialize)]
pub struct Tier {
    /// `full` | `fluency` | `mini`.
    pub name: String,
    /// Embedding dimensionality (300 for all current tiers).
    pub dims: u32,
    /// Vocabulary rows.
    pub vocab_size: u32,
    /// Quantization descriptor: `None` (full), `"int8-per-row"` (the
    /// current tiers), `"int4-per-row"` (future B1 artifacts).
    pub quantization: Option<String>,
}

/// Primary + mirror download URLs.
#[derive(Debug, Clone, Deserialize)]
pub struct Urls {
    /// The GitHub release URL, or null when the registry was generated
    /// from an untagged tree.
    pub primary: Option<String>,
    /// The raw-branch mirror.
    pub mirror: String,
}

impl Registry {
    /// Parse and validate registry JSON (`spec` must be [`SPEC`]).
    pub fn parse(json: &str) -> Result<Self, ResourceError> {
        let registry: Self = serde_json::from_str(json).map_err(ResourceError::Json)?;
        if registry.spec != SPEC {
            return Err(ResourceError::UnsupportedSpec(registry.spec));
        }
        Ok(registry)
    }

    /// Resolve a resource id (`kotoshu://models/{language}/{tier}`).
    pub fn resource_by_id(&self, id: &str) -> Option<&Resource> {
        self.resources.get(id)
    }

    /// Resolve `(language, tier)` → resource. The id is assembled as
    /// `kotoshu://models/{language}/{tier}` and the entry's own
    /// `language`/`tier.name` are cross-checked (a registry whose keys
    /// disagree with its entries is refused, not papered over).
    pub fn resource(&self, language: &str, tier: &str) -> Option<&Resource> {
        let id = format!("kotoshu://models/{language}/{tier}");
        let resource = self.resource_by_id(&id)?;
        if resource.language == language && resource.tier.name == tier {
            Some(resource)
        } else {
            None
        }
    }
}

/// Errors of the resource layer.
#[derive(Debug)]
pub enum ResourceError {
    /// Registry `spec` is not [`SPEC`].
    UnsupportedSpec(String),
    /// No resource for `(language, tier)`.
    UnknownResource { language: String, tier: String },
    /// Malformed registry or vocab JSON.
    Json(serde_json::Error),
    /// Local I/O failure.
    Io {
        path: PathBuf,
        source: std::io::Error,
    },
    /// Downloaded bytes do not match the registry sha256.
    Checksum {
        path: String,
        expected: String,
        actual: String,
    },
    /// The resource has no downloadable URL.
    NoUrl { language: String, tier: String },
    /// Download failed (curl absent or errored).
    Fetch { url: String, source: String },
}

impl fmt::Display for ResourceError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnsupportedSpec(spec) => {
                write!(f, "unsupported registry spec {spec:?} (expected {SPEC:?})")
            }
            Self::UnknownResource { language, tier } => {
                write!(f, "no registry resource for {language}/{tier}")
            }
            Self::Json(source) => write!(f, "malformed JSON: {source}"),
            Self::Io { path, source } => write!(f, "{}: {source}", path.display()),
            Self::Checksum {
                path,
                expected,
                actual,
            } => write!(
                f,
                "sha256 mismatch for {path}: expected {expected}, got {actual}"
            ),
            Self::NoUrl { language, tier } => write!(f, "{language}/{tier} has no download URL"),
            Self::Fetch { url, source } => write!(f, "download {url} failed: {source}"),
        }
    }
}

impl std::error::Error for ResourceError {}

impl From<serde_json::Error> for ResourceError {
    fn from(source: serde_json::Error) -> Self {
        Self::Json(source)
    }
}

/// sha256 of `bytes` as lowercase hex.
pub fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest {
        use fmt::Write as _;
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}

/// Verify `bytes` against a registry `sha256` (hex, case-insensitive).
pub fn verify_sha256(bytes: &[u8], expected: &str) -> Result<(), ResourceError> {
    let actual = sha256_hex(bytes);
    if actual.eq_ignore_ascii_case(expected) {
        Ok(())
    } else {
        Err(ResourceError::Checksum {
            path: String::new(),
            expected: expected.to_owned(),
            actual,
        })
    }
}

/// The local cache root, honoring (in order) `KOTOSHU_CACHE_PATH`,
/// `XDG_CACHE_HOME/kotoshu`, and `$HOME/.cache/kotoshu` — the same
/// resolution as the gem's `Kotoshu::Paths`.
pub fn cache_root() -> PathBuf {
    if let Some(path) = std::env::var_os("KOTOSHU_CACHE_PATH")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
    {
        return path;
    }
    if let Some(xdg) = std::env::var_os("XDG_CACHE_HOME").filter(|value| !value.is_empty()) {
        return PathBuf::from(xdg).join("kotoshu");
    }
    match std::env::var_os("HOME").filter(|value| !value.is_empty()) {
        Some(home) => PathBuf::from(home).join(".cache").join("kotoshu"),
        None => std::env::temp_dir().join("kotoshu"),
    }
}

/// Download `url` through the system `curl`. Hosts without curl (or
/// wanting their own HTTP stack) inject a fetcher via
/// [`ResourceCache::ensure_model_with`].
pub fn fetch_url_curl(url: &str) -> Result<Vec<u8>, ResourceError> {
    let output = std::process::Command::new("curl")
        .arg("-fsSL")
        .arg("--")
        .arg(url)
        .output()
        .map_err(|source| ResourceError::Fetch {
            url: url.to_owned(),
            source: format!("cannot run curl: {source}"),
        })?;
    if output.status.success() {
        Ok(output.stdout)
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr).trim().to_owned();
        Err(ResourceError::Fetch {
            url: url.to_owned(),
            source: stderr,
        })
    }
}

/// Local paths of a cached model.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModelPaths {
    /// The `.onnx` graph.
    pub onnx: PathBuf,
    /// The `.vocab.json` sibling.
    pub vocab: PathBuf,
}

/// The model cache under a local directory.
#[derive(Debug, Clone)]
pub struct ResourceCache {
    root: PathBuf,
}

impl Default for ResourceCache {
    fn default() -> Self {
        Self::new()
    }
}

impl ResourceCache {
    /// Cache at [`cache_root`] (env-honoring).
    pub fn new() -> Self {
        Self { root: cache_root() }
    }

    /// Cache at an explicit root (tests and host injection).
    pub fn with_root(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    /// The cache root.
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Where the tier `.onnx` lives:
    /// `{root}/models/{language}/{tier}.onnx`.
    pub fn model_path(&self, language: &str, tier: &str) -> PathBuf {
        self.root
            .join("models")
            .join(language)
            .join(format!("{tier}.onnx"))
    }

    /// Where the tier `.vocab.json` lives:
    /// `{root}/models/{language}/{tier}.vocab.json`.
    pub fn vocab_path(&self, language: &str, tier: &str) -> PathBuf {
        self.root
            .join("models")
            .join(language)
            .join(format!("{tier}.vocab.json"))
    }

    /// Ensure `(language, tier)` is cached and sha-verified, downloading
    /// through the system curl when needed.
    pub fn ensure_model(
        &self,
        registry: &Registry,
        language: &str,
        tier: &str,
    ) -> Result<ModelPaths, ResourceError> {
        self.ensure_model_with(registry, language, tier, fetch_url_curl)
    }

    /// [`ResourceCache::ensure_model`] with an injected fetcher — the
    /// seam hosts use to bring their own HTTP stack.
    ///
    /// Semantics: a cached model is (re)used only if its bytes match the
    /// registry sha256; a corrupt or stale file is replaced by a fresh
    /// download (primary URL, then mirror), verified *before* the
    /// on-disk file is atomically replaced (write to `.part`, rename).
    /// The vocab.json has no registry checksum (v1), so it is only
    /// downloaded when absent.
    pub fn ensure_model_with(
        &self,
        registry: &Registry,
        language: &str,
        tier: &str,
        mut fetch: impl FnMut(&str) -> Result<Vec<u8>, ResourceError>,
    ) -> Result<ModelPaths, ResourceError> {
        let resource = registry
            .resource(language, tier)
            .ok_or(ResourceError::UnknownResource {
                language: language.to_owned(),
                tier: tier.to_owned(),
            })?;

        let model_path = self.model_path(language, tier);
        let vocab_path = self.vocab_path(language, tier);

        if !self.model_is_fresh(&model_path, &resource.sha256) {
            let bytes = self.download(resource, &mut fetch)?;
            self.write_atomic(&model_path, &bytes)?;
        }
        if !vocab_path.is_file()
            && let Some(vocab_url) = resource.vocab_url.as_deref().filter(|url| !url.is_empty())
        {
            let bytes = fetch(vocab_url)?;
            self.write_atomic(&vocab_path, &bytes)?;
        }

        Ok(ModelPaths {
            onnx: model_path,
            vocab: vocab_path,
        })
    }

    /// Cached-and-verified check for the `.onnx` path.
    fn model_is_fresh(&self, path: &Path, expected_sha256: &str) -> bool {
        let Ok(bytes) = std::fs::read(path) else {
            return false;
        };
        verify_sha256(&bytes, expected_sha256).is_ok()
    }

    /// Primary-then-mirror download with checksum enforcement.
    fn download(
        &self,
        resource: &Resource,
        fetch: &mut impl FnMut(&str) -> Result<Vec<u8>, ResourceError>,
    ) -> Result<Vec<u8>, ResourceError> {
        let mut urls: Vec<&str> = Vec::new();
        if let Some(primary) = resource
            .urls
            .primary
            .as_deref()
            .filter(|url| !url.is_empty())
        {
            urls.push(primary);
        }
        urls.push(resource.urls.mirror.as_str());

        let mut last = ResourceError::NoUrl {
            language: resource.language.clone(),
            tier: resource.tier.name.clone(),
        };
        for url in urls {
            match fetch(url) {
                Ok(bytes) => match verify_sha256(&bytes, &resource.sha256) {
                    Ok(()) => return Ok(bytes),
                    Err(error) => {
                        last = match error {
                            ResourceError::Checksum {
                                expected, actual, ..
                            } => ResourceError::Checksum {
                                path: url.to_owned(),
                                expected,
                                actual,
                            },
                            other => other,
                        };
                    }
                },
                Err(error) => last = error,
            }
        }
        Err(last)
    }

    /// Write bytes to `path` atomically (`.part` sibling + rename).
    fn write_atomic(&self, path: &Path, bytes: &[u8]) -> Result<(), ResourceError> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|source| ResourceError::Io {
                path: parent.to_owned(),
                source,
            })?;
        }
        let part = path.with_extension("part");
        std::fs::write(&part, bytes).map_err(|source| ResourceError::Io {
            path: part.clone(),
            source,
        })?;
        std::fs::rename(&part, path).map_err(|source| ResourceError::Io {
            path: part.clone(),
            source,
        })
    }
}

#[cfg(test)]
#[allow(dead_code)]
fn error_matches(error: &ResourceError) -> Option<(String, String)> {
    match error {
        ResourceError::Checksum {
            expected, actual, ..
        } => Some((expected.clone(), actual.clone())),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A trimmed but real excerpt of the v1.0.1 registry (values copied
    /// from the models repo's registry.json).
    const REGISTRY_EXCERPT: &str = r#"{
      "spec": "kotoshu.resources/v1",
      "registry_version": 1,
      "release_tag": "v1.0.1",
      "resources": {
        "kotoshu://models/en/mini": {
          "type": "model", "language": "en",
          "tier": { "name": "mini", "dims": 300, "vocab_size": 10000,
                    "quantization": "int8-per-row" },
          "version": "1.0.1",
          "urls": {
            "primary": "https://example.invalid/fasttext.en.mini.onnx",
            "mirror": "https://example.invalid/raw/fasttext.en.mini.onnx" },
          "vocab_url": "https://example.invalid/fasttext.en.mini.vocab.json",
          "sha256": "d81f36c5e0097414db95d48406ce615161dd07c697996fe973297186279d5e2f",
          "size_bytes": 3040752, "license": "CC-BY-SA-3.0",
          "min_engine_version": "0.7", "eval_ref": "eval/reports/en.mini.json"
        },
        "kotoshu://models/en/full": {
          "type": "model", "language": "en",
          "tier": { "name": "full", "dims": 300, "vocab_size": 100000,
                    "quantization": null },
          "version": "1.0.1",
          "urls": { "primary": null, "mirror": "https://example.invalid/raw/fasttext.en.onnx" },
          "vocab_url": null,
          "sha256": "cf826747600aa353d9be18a47e63cbd3929e742088af338096edcf54aad17d36",
          "size_bytes": 120000415, "license": "CC-BY-SA-3.0",
          "min_engine_version": "0.7", "eval_ref": null
        }
      }
    }"#;

    #[test]
    fn parse_and_resolve_the_real_shape() {
        let registry = Registry::parse(REGISTRY_EXCERPT).unwrap();
        assert_eq!(registry.release_tag.as_deref(), Some("v1.0.1"));

        let mini = registry.resource("en", "mini").unwrap();
        assert_eq!(mini.language, "en");
        assert_eq!(mini.tier.name, "mini");
        assert_eq!(mini.tier.dims, 300);
        assert_eq!(mini.tier.vocab_size, 10000);
        assert_eq!(mini.tier.quantization.as_deref(), Some("int8-per-row"));
        assert_eq!(mini.size_bytes, 3040752);
        assert_eq!(
            mini.urls.primary.as_deref(),
            Some("https://example.invalid/fasttext.en.mini.onnx")
        );
        assert_eq!(
            mini.sha256,
            "d81f36c5e0097414db95d48406ce615161dd07c697996fe973297186279d5e2f"
        );

        let full = registry.resource("en", "full").unwrap();
        assert_eq!(full.tier.quantization, None);
        assert_eq!(full.urls.primary, None);
        assert_eq!(full.vocab_url, None);

        assert!(registry.resource("en", "nano").is_none());
        assert!(registry.resource("xx", "mini").is_none());
    }

    #[test]
    fn wrong_spec_is_refused() {
        let error = Registry::parse("{\"spec\":\"kotoshu.resources/v2\",\"registry_version\":1,\"release_tag\":null,\"resources\":{}}")
            .unwrap_err();
        assert!(error.to_string().contains("kotoshu.resources/v2"));
        assert!(matches!(error, ResourceError::UnsupportedSpec(_)));
    }

    #[test]
    fn sha256_known_answer_and_mismatch() {
        // sha256("hello")
        assert_eq!(
            sha256_hex(b"hello"),
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
        );
        verify_sha256(
            b"hello",
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824",
        )
        .unwrap();
        // Case-insensitive compare of the expected hex.
        verify_sha256(
            b"hello",
            "2CF24DBA5FB0A30E26E83B2AC5B9E29E1B161E5C1FA7425E73043362938B9824",
        )
        .unwrap();
        let error = verify_sha256(
            b"world",
            "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824",
        )
        .unwrap_err();
        assert!(matches!(error, ResourceError::Checksum { .. }));
    }

    fn temp_root(tag: &str) -> ResourceCache {
        ResourceCache::with_root(
            std::env::temp_dir().join(format!("kotoshu-rs-resource-{tag}-{}", std::process::id())),
        )
    }

    #[test]
    fn cache_layout_is_registry_stable() {
        let cache = ResourceCache::with_root("/tmp/kotoshu-cache");
        assert_eq!(
            cache.model_path("en", "mini"),
            PathBuf::from("/tmp/kotoshu-cache/models/en/mini.onnx")
        );
        assert_eq!(
            cache.vocab_path("en", "mini"),
            PathBuf::from("/tmp/kotoshu-cache/models/en/mini.vocab.json")
        );
    }

    #[test]
    fn ensure_model_uses_verified_cache_without_fetching() {
        let cache = temp_root("cached");
        let model = cache.model_path("en", "mini");
        std::fs::create_dir_all(model.parent().unwrap()).unwrap();
        std::fs::write(&model, b"verified-bytes").unwrap();

        let no_network = |url: &str| -> Result<Vec<u8>, ResourceError> {
            Err(ResourceError::Fetch {
                url: url.to_owned(),
                source: "network disabled in test".to_owned(),
            })
        };

        // A registry expecting sha256("verified-bytes"): the cached
        // model passes verification, but the vocab is absent and the
        // (disabled) download attempt for it proves the model itself
        // was NOT re-fetched.
        let registry = Registry::parse(&REGISTRY_EXCERPT.replace(
            "d81f36c5e0097414db95d48406ce615161dd07c697996fe973297186279d5e2f",
            &sha256_hex(b"verified-bytes"),
        ))
        .unwrap();
        let error = cache
            .ensure_model_with(&registry, "en", "mini", no_network)
            .unwrap_err();
        assert!(matches!(error, ResourceError::Fetch { .. }));
        assert!(
            error.to_string().contains("vocab"),
            "expected the vocab download to be the failure, got: {error}"
        );
        assert_eq!(std::fs::read(&model).unwrap(), b"verified-bytes");

        // With the vocab also cached, everything resolves fully offline.
        std::fs::write(cache.vocab_path("en", "mini"), b"{}").unwrap();
        let paths = cache
            .ensure_model_with(&registry, "en", "mini", no_network)
            .unwrap();
        assert_eq!(paths.onnx, model);
        assert_eq!(paths.vocab, cache.vocab_path("en", "mini"));
    }

    #[test]
    fn ensure_model_downloads_verifies_and_replaces_atomically() {
        let cache = temp_root("download");

        // Serve the same bytes from both URLs; the registry entry's sha
        // is repointed at sha256(b"real") so only those bytes verify.
        let sha = sha256_hex(b"real");
        let registry = Registry::parse(&REGISTRY_EXCERPT.replace(
            "d81f36c5e0097414db95d48406ce615161dd07c697996fe973297186279d5e2f",
            &sha,
        ))
        .unwrap();

        let mut calls: Vec<String> = Vec::new();
        {
            let mut fetch = |url: &str| -> Result<Vec<u8>, ResourceError> {
                calls.push(url.to_owned());
                match url.rsplit('/').next().unwrap_or("") {
                    "fasttext.en.mini.onnx" => Ok(b"real".to_vec()),
                    "fasttext.en.mini.vocab.json" => {
                        Ok(b"{\"vocab_size\":0,\"word_to_idx\":{}}".to_vec())
                    }
                    _ => Err(ResourceError::Fetch {
                        url: url.to_owned(),
                        source: "not found".to_owned(),
                    }),
                }
            };

            let paths = cache
                .ensure_model_with(&registry, "en", "mini", &mut fetch)
                .unwrap();
            assert_eq!(std::fs::read(&paths.onnx).unwrap(), b"real");
            assert!(paths.vocab.is_file());
            assert!(!paths.onnx.with_extension("part").exists());

            // Corrupt the cache; the next ensure re-downloads and heals it.
            std::fs::write(&paths.onnx, b"corrupted").unwrap();
            let healed = cache
                .ensure_model_with(&registry, "en", "mini", &mut fetch)
                .unwrap();
            assert_eq!(std::fs::read(&healed.onnx).unwrap(), b"real");
        }

        // Primary was tried first; the corrupted round re-fetched again.
        assert_eq!(calls[0], "https://example.invalid/fasttext.en.mini.onnx");
        assert!(calls.iter().filter(|url| url.ends_with(".onnx")).count() >= 2);
    }

    #[test]
    fn checksum_mismatch_falls_through_to_the_mirror() {
        let cache = temp_root("mirror");
        let fetch = |url: &str| -> Result<Vec<u8>, ResourceError> {
            if url.contains("/raw/") {
                Ok(b"good-mirror".to_vec())
            } else {
                Ok(b"bad-primary".to_vec())
            }
        };
        let sha = sha256_hex(b"good-mirror");
        let registry = Registry::parse(&REGISTRY_EXCERPT.replace(
            "d81f36c5e0097414db95d48406ce615161dd07c697996fe973297186279d5e2f",
            &sha,
        ))
        .unwrap();

        let paths = cache
            .ensure_model_with(&registry, "en", "mini", fetch)
            .unwrap();
        assert_eq!(std::fs::read(&paths.onnx).unwrap(), b"good-mirror");
    }

    #[test]
    fn unknown_resource_is_reported() {
        let registry = Registry::parse(REGISTRY_EXCERPT).unwrap();
        let cache = temp_root("unknown");
        let error = cache
            .ensure_model_with(&registry, "ja", "mini", fetch_url_curl)
            .unwrap_err();
        assert!(matches!(error, ResourceError::UnknownResource { .. }));
        assert!(error.to_string().contains("ja/mini"));
    }
}
